package com.savoskinsemyon.projectdb;

public enum ProjectWindows {
    START_PAGE,
    TABLE_CHANGE_AIRPLANE_PAGE,
    TABLE_CHANGE_PLACE_PAGE,
    TABLE_SELECTION_PAGE,
    REQUEST_SELECTION_PAGE,
    REQUEST_PASSENGER_PAGE,
    REQUEST_AIRPLANE_PAGE,
    REQUEST_STAFF_PAGE,
    REQUEST_FLIGHTS_PAGE,
}
